### ISSUE TITLE
Sending different images to each eye

### ISSUE THREAD

**Issue by Francodibrotsy** [BioMotionLab/TUX#42] opened 2021-12-28 19:14 UTC
Hi!

I was programing an experiment and I want to work with binocular rivalry, but I don't know how to send different images to each eye. Thanks!

**Comment by AdamBebko** [comment] 2021-12-28 22:24
This is a problem I have faced as well. If you use steamVR plugin without using unity’s new openXR implementation, vr cameras should have a “Target eye” property. The problem is that in unity’s new XR plugin management system in either URP or HDRP, they have removed that functionality and I have yet to find a solution. So as long as you use the built in render pipeline you should be able to put two cameras in the scene and choose the target eye. 

Hope that helps!

**Comment by AdamBebko** [comment] 2022-02-13 19:58
assuming that fixed the problem. closing this. reopen if you have problems.

**Closed by AdamBebko** 2022-02-13 19:58 UTC
